// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import { Inter } from "next/font/google";
import { ClerkWrapper } from '../clerk';
import "./globals.css";
import Provider from "./provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Toingg",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkWrapper>
      <html lang="en">
        <body className={inter.className}>
          <div className="flex min-h-screen h-full">
            <Provider>{children}</Provider>
          </div>
        </body>
      </html>
    </ClerkWrapper>
  );
}
